"""Static astrologer catalog — mirrors src/content/astrologersData.ts"""

ASTROLOGER_SEED_ROWS = [
    {
        "legacy_id": 301,
        "slug": "acharya-vidyabhushan-ab0000012d",
        "name": "Acharya Vidyabhushan",
        "specialty": "Vedic Astrology & Kundali Expert",
        "title": "Vedic Astrologer & Spiritual Guide",
        "tagline": "Generations of Jyotish wisdom, distilled into honest and deeply actionable guidance for the modern seeker.",
        "bio": "Guiding seekers with precise chart readings, dasha analysis, and practical remedies rooted in classical Vedic tradition.",
        "bio_long": "With over 18 years of practice, Acharya Vidyabhushan specialises in birth-chart analysis, planetary periods (dashas), and remedial measures aligned with classical Jyotish. He has guided more than 12,000 seekers across India and abroad.\n\nTrained in traditional gurukul methods and refined through years of live consultations, he focuses on career transitions, marriage timing, health concerns, and spiritual growth—with clear, actionable guidance rather than vague predictions.\n\nSessions are structured, confidential, and designed to leave you with practical next steps you can apply immediately.",
        "rating_avg": 4.95,
        "review_count": 1420,
        "consultation_count": 12450,
        "experience_years": 18,
        "price_per_minute": 100,
        "online_status": "online",
        "languages": "Hindi, English, Sanskrit",
        "avatar_url": "/astrologers/vidyabhushan-avatar.jpg?v=2",
        "portrait_url": "/astrologers/vidyabhushan-portrait.jpg?v=2",
        "specialities": [
            {"title": "Janma Kundali", "description": "Detailed birth-chart analysis with dasha predictions."},
            {"title": "Dasha & Transit", "description": "Timing of events through Vimshottari and Gochar readings."},
            {"title": "Match-making", "description": "Gun Milan and compatibility for marriage decisions."},
            {"title": "Career & Finance", "description": "Planetary guidance for growth, promotions, and stability."},
            {"title": "Remedies", "description": "Mantra, gemstone, and puja recommendations from classical texts."},
        ],
    },
    {
        "legacy_id": 302,
        "slug": "priya-chawla-ab0000012e",
        "name": "Priya Chawla",
        "specialty": "Tarot Reading & Relationship Guide",
        "title": "Tarot Reader & Relationship Counselor",
        "tagline": "Intuitive clarity for love, family, and life decisions—compassionate guidance you can trust.",
        "bio": "Specializing in relationship clarity, emotional healing, and intuitive Tarot spreads for life-changing decisions.",
        "bio_long": "Priya blends intuitive Tarot with counselling-style conversation to help you navigate love, family, and major life choices. Over 8 years she has supported thousands of clients through breakups, reconciliations, and new beginnings.\n\nHer readings are warm, confidential, and oriented toward practical next steps—never fear-based. She is especially sought after for relationship dilemmas, career crossroads, and emotional healing after difficult phases.\n\nEach session combines spread interpretation with grounded advice you can act on the same day.",
        "rating_avg": 4.88,
        "review_count": 890,
        "consultation_count": 6200,
        "experience_years": 8,
        "price_per_minute": 55,
        "online_status": "online",
        "languages": "Hindi, English",
        "avatar_url": "/astrologers/priya-avatar.jpg?v=2",
        "portrait_url": "/astrologers/priya-portrait.jpg?v=2",
        "specialities": [
            {"title": "Tarot Reading", "description": "Celtic cross and relationship spreads for clear answers."},
            {"title": "Love & Marriage", "description": "Clarity on partners, timing, and emotional patterns."},
            {"title": "Career Guidance", "description": "Choices aligned with your energy and life path."},
            {"title": "Emotional Healing", "description": "Support through anxiety, loss, and major transitions."},
        ],
    },
    {
        "legacy_id": 303,
        "slug": "shastri-govind-dev-ab0000012f",
        "name": "Shastri Govind Dev",
        "specialty": "KP System & Gemology Guru",
        "title": "KP Astrologer & Gemology Expert",
        "tagline": "Precision timing and verified gemstones—Krishnamurti Paddhati for decisive life events.",
        "bio": "Expert in KP astrology, gemstone recommendations, and sub-lord techniques for accurate timing of events.",
        "bio_long": "Shastri Govind Dev applies the Krishnamurti Paddhati system for sharp event timing and recommends gemstones only after rigorous chart verification. Ideal for clients seeking precision on promotions, litigation, property, and investments.\n\nWith 15 years of practice and training under senior KP masters, he has become a trusted name for corporate leaders and families needing exact Muhurat windows.\n\nConsultations are analytical, documented, and focused on verifiable outcomes.",
        "rating_avg": 4.91,
        "review_count": 1105,
        "consultation_count": 9800,
        "experience_years": 15,
        "price_per_minute": 75,
        "online_status": "online",
        "languages": "Hindi, English",
        "avatar_url": "/astrologers/govind-avatar.jpg?v=2",
        "portrait_url": "/astrologers/govind-portrait.jpg?v=2",
        "specialities": [
            {"title": "KP Horoscope", "description": "Sub-lord analysis for precise event timing."},
            {"title": "Gemology", "description": "Certified gemstone recommendations after chart study."},
            {"title": "Property & Legal", "description": "Favourable periods for purchase, sale, and disputes."},
            {"title": "Business Timing", "description": "Launch dates and partnership compatibility."},
        ],
    },
    {
        "legacy_id": 304,
        "slug": "kabir-vats-ab00000130",
        "name": "Kabir Vats",
        "specialty": "Vedic Numerology & Astro-Vastu",
        "title": "Numerologist & Astro-Vastu Consultant",
        "tagline": "Harmonize your name, home, and numbers with planetary vibrations for lasting success.",
        "bio": "Blending numerology with Vastu principles to harmonize your home, career path, and personal name vibrations.",
        "bio_long": "Kabir integrates name numerology, mobile and business number analysis, and residential Vastu corrections. Consultations help families and entrepreneurs align their environment with favourable planetary vibrations.\n\nOver a decade he has advised startups, homeowners, and students on name changes, office layout, and lucky dates for launches.\n\nSessions include a written summary of corrections and simple remedies you can implement without major renovation.",
        "rating_avg": 4.85,
        "review_count": 640,
        "consultation_count": 4100,
        "experience_years": 10,
        "price_per_minute": 60,
        "online_status": "online",
        "languages": "Hindi, English",
        "avatar_url": "/astrologers/kabir-avatar.jpg?v=2",
        "portrait_url": "/astrologers/kabir-portrait.jpg?v=2",
        "specialities": [
            {"title": "Name Numerology", "description": "Personal and business name vibration analysis."},
            {"title": "Astro-Vastu", "description": "Room-wise corrections for home and office energy."},
            {"title": "Mobile & Vehicle", "description": "Lucky numbers for phones, plates, and accounts."},
            {"title": "Life Path Numbers", "description": "Core strengths and challenges from birth date."},
        ],
    },
    {
        "legacy_id": 305,
        "slug": "dr-meera-iyer-ab00000131",
        "name": "Dr. Meera Iyer",
        "specialty": "Palmistry & Prashna Shastra",
        "title": "Palmist & Prashna Shastra Expert",
        "tagline": "Immediate answers when birth details are missing—palmistry and horary astrology combined.",
        "bio": "Offering palmistry insights and Prashna readings for immediate answers to pressing life questions.",
        "bio_long": "Dr. Meera Iyer provides Prashna (horary) readings when birth details are incomplete, alongside traditional palmistry. She is sought after for urgent decisions on travel, surgery timing, and relationship dilemmas.\n\nWith 12 years of clinical and spiritual practice, she bridges classical Shastra with empathetic counselling for modern families.\n\nIdeal for clients who need same-day clarity on yes-or-no questions.",
        "rating_avg": 4.92,
        "review_count": 756,
        "consultation_count": 5300,
        "experience_years": 12,
        "price_per_minute": 65,
        "online_status": "online",
        "languages": "Hindi, English, Tamil",
        "avatar_url": "/astrologers/meera-avatar.jpg?v=2",
        "portrait_url": "/astrologers/meera-portrait.jpg?v=2",
        "specialities": [
            {"title": "Prashna Shastra", "description": "Horary charts for urgent yes/no questions."},
            {"title": "Palmistry", "description": "Life line, fate line, and marriage line interpretation."},
            {"title": "Health Timing", "description": "Favourable windows for procedures and recovery."},
            {"title": "Travel & Relocation", "description": "Safety and success for moves abroad."},
        ],
    },
    {
        "legacy_id": 306,
        "slug": "pandit-ramesh-joshi-ab00000132",
        "name": "Pandit Ramesh Joshi",
        "specialty": "Muhurat & Ritual Astrology",
        "title": "Muhurat Specialist & Ritual Astrologer",
        "tagline": "Sacred timing for weddings, ventures, and pujas—Panchang precision with clear ritual guidance.",
        "bio": "Calculating auspicious Muhurats and prescribing sacred rituals for weddings, ventures, and spiritual milestones.",
        "bio_long": "Pandit Ramesh Joshi has officiated and timed hundreds of pujas and vivahas. He selects Muhurats using Panchang, local latitude corrections, and family gotra considerations, and explains each ritual step in plain language.\n\nWith 22 years of experience he is trusted by families across Gujarat and Maharashtra for griha pravesh, mundan, and corporate inaugurations.\n\nEvery consultation includes written Muhurat slots and a simple checklist for priests or family members.",
        "rating_avg": 4.89,
        "review_count": 980,
        "consultation_count": 11200,
        "experience_years": 22,
        "price_per_minute": 110,
        "online_status": "online",
        "languages": "Hindi, Sanskrit",
        "avatar_url": "/astrologers/ramesh-avatar.jpg?v=2",
        "portrait_url": "/astrologers/ramesh-portrait.jpg?v=2",
        "specialities": [
            {"title": "Vivah Muhurat", "description": "Wedding dates aligned with couple charts and Panchang."},
            {"title": "Griha Pravesh", "description": "Auspicious entry timings for new homes."},
            {"title": "Business Launch", "description": "Opening ceremonies and partnership beginnings."},
            {"title": "Puja Vidhi", "description": "Step-by-step ritual guidance for family ceremonies."},
        ],
    },
]
